using System.Text.RegularExpressions;
using Dapper;
using Javideo.Worker.Db;

namespace Javideo.Worker.Services;

/// <summary>
/// Scans a library's directories for media files with canonical 番号 naming
/// (mp4 / mkv / strm). Unavailable directories are skipped and logged.
/// </summary>
public sealed class Scanner
{
    private readonly DbConnectionFactory _db;

    // Canonical 番号 patterns — tried in order, first match wins.
    private static readonly Regex[] Patterns =
    [
        // Standard: 2-6 letters + optional hyphen + 2-5 digits (ABP-123, SSIS-456)
        new(@"([A-Za-z]{2,6})-?(\d{2,5})", RegexOptions.Compiled),
        // Sub-series letter: 2-6 letters + hyphen + 1 letter + digits (MKBD-S03, MKD-S93)
        new(@"([A-Za-z]{2,6})-([A-Za-z])(\d{2,5})", RegexOptions.Compiled),
        // Single-letter prefix + 3-5 digits (n0646, N0919, RB007)
        new(@"([A-Za-z])0?(\d{3,5})", RegexOptions.Compiled),
        // Two-letter prefix + digits (RB007, LB0009, SR138)
        new(@"([A-Za-z]{2})0?(\d{3,5})", RegexOptions.Compiled),
        // Date-number uncensored (092211-813, 050426_001)
        new(@"(\d{6})[-_](\d{2,3})", RegexOptions.Compiled),
    ];

    private static readonly HashSet<string> MediaExts =
        new(StringComparer.OrdinalIgnoreCase) { ".mp4", ".mkv", ".strm" };

    public Scanner(DbConnectionFactory db) => _db = db;

    public record ScanResult(int AvailableDirs, int SkippedDirs, List<ScannedFile> Files, List<string> Logs);
    public record ScannedFile(string Number, string FilePath, string FileName);

    public async Task<ScanResult> ScanLibraryAsync(long libraryId)
    {
        await using var c = _db.Create();
        await c.OpenAsync();
        var dirs = (await c.QueryAsync<string>(
            "SELECT path FROM library_directories WHERE library_id=@id", new { id = libraryId })).ToList();

        var files = new List<ScannedFile>();
        var logs = new List<string>();
        int available = 0, skipped = 0;

        foreach (var dir in dirs)
        {
            if (!Directory.Exists(dir))
            {
                skipped++;
                logs.Add($"[跳过] 目录不可用: {dir}");
                continue;
            }
            available++;
            try
            {
                foreach (var file in EnumerateMedia(dir))
                {
                    var num = RecognizeNumber(file.Name);
                    if (num != null)
                        files.Add(new ScannedFile(num, file.FullName, file.Name));
                    else
                        logs.Add($"[未识别] {file.FullName} — 未匹配到番号");
                }
            }
            catch (Exception ex)
            {
                logs.Add($"[错误] 扫描 {dir} 失败: {ex.Message}");
            }
        }
        return new ScanResult(available, skipped, files, logs);
    }

    /// <summary>Recognize a 番号 from a file name, returning the raw match
    /// as-is (no uppercasing, no zero-padding, no hyphen insertion).</summary>
    public static string? RecognizeNumber(string fileName)
    {
        var name = Path.GetFileNameWithoutExtension(fileName);
        foreach (var regex in Patterns)
        {
            var m = regex.Match(name);
            if (m.Success) return m.Value;
        }
        return null;
    }

    private static IEnumerable<FileInfo> EnumerateMedia(string dir)
    {
        var di = new DirectoryInfo(dir);
        foreach (var fi in di.EnumerateFiles("*", SearchOption.AllDirectories))
        {
            // Skip trailer files ({番号}-trailer.mp4) — they're generated by us.
            if (MediaExts.Contains(fi.Extension) && !fi.Name.Contains("-trailer", StringComparison.OrdinalIgnoreCase))
                yield return fi;
        }
    }
}
